version: '3.3'


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: 
      bash -c "python manage.py migrate && gunicorn ecourse.wsgi:application -b 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    # expose:
    # - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./.env

  redis:
    container_name: redis_1
    image: 'redis:alpine'
    hostname: redis


  nginx:
    image: nginx
    hostname: nginx
    ports:
      - '5555:8000'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./:/code/
    depends_on:
      - web

volumes:
  postgres_data: