version: '3.3'


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: 
      bash -c "python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ecourse/:/usr/src/app/
    ports:
      - 8000:8000
    # expose:
    # - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./.env

  redis:
    container_name: redis_1
    image: 'redis:alpine'
    hostname: redis


  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web

volumes:
  postgres_data: